name: Add tag on demo dataset

on:
  workflow_dispatch: # exécution manuelle uniquement

jobs:
  add-tag-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dépendances
        run: |
          pip install datagouv-client requests

      - name: Run addTagDemo script
        env:
          DEMO_DATA_GOUV_KEY: ${{ secrets.DEMO_DATA_GOUV_KEY }}
        run: |
          python DataGouv/scripts/addTagDemo.py
