name: Exécution planifiée de dataAutomation.py

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 7h UTC
  workflow_dispatch:  # Permet le lancement manuel

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install pandas requests

      - name: Exécuter le script Python
        run: python dataAutomation.py

      - name: Configurer l’identité Git
        run: |
          git config --global user.name 'Bot Culture Data'
          git config --global user.email 'donnees@tipicomm.com'

      - name: Commit du fichier généré
        run: |
          git add ressources_csv_culture.csv
          git commit -m "📄 Mise à jour automatique du fichier CSV [skip ci]" || echo "Aucun changement à commiter"

      - name: Pousser les modifications
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
