name: Exécution planifiée de dataAutomation.py

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 7h (UTC)
  workflow_dispatch:  # Permet de le lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install pandas requests

      - name: Exécuter le script Python
        run: python dataAutomation.py
