name: 📝 Exemples propriétés CSV - CartoDataMC

on:
  workflow_dispatch:

jobs:
  enrich-exemples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🐍 Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Installer les dépendances
        run: |
          pip install pandas requests

      - name: 📝 Exécuter le script d’exemples de propriétés
        run: python CartoDataMC/exemples_proprietes.py

      - name: 💾 Ajouter le fichier généré au dépôt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CartoDataMC/cartographie_culture_properties_exemples.csv
          git commit -m "📝 Ajout des exemples de valeurs pour chaque propriété"
          git push
        continue-on-error: true
